spring:
 application:
  name: config-dev
Eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://service-regsistry-microservices-hotel.onrender.com/eureka/
